name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate-snake:
    permissions:
      contents: write
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - uses: Platane/snk@v3
        with:
          github_user_name: s3nkuuu
          outputs: |
            dist/github-snake-dark.svg?palette=github-dark
            
  generate-name:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    
    steps:
      - name: Generate name animation  
        uses: keshavsingh4522/Github-profile-name-writer@main
        with:
          github-user-name: s3nkuuu
          
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: snake
          build_dir: .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
